### ISSUE TITLE
How was the test data simulated?

### ISSUE THREAD

**Issue by rchikhi** [ablab/tandemQUAST#3]
Hi,

we are looking to use your provided example data for another purpose, and were wondering how the reads were simulated. It seems that `test_data/simulated_reads.fasta` was produced by running NanoSim on a different reference than `test_data/simulated_polished.fa` (read headers start with `>flanked-sim-tr[..]`).  Any chance you could please provide the `flanked-sim-tr` reference file? 

thanks in advance,

Rayan

**Comment by almiheenko** [comment]
Hi Rayan,

Sorry for the delay! I attach the reference file. Please notice that this file contains 200 kbp of flanking non-tandem repeat sequence on both ends. 

Best regards,
Alla
[flanked_tandem_repeat.fasta.zip](https://github.com/ablab/TandemTools/files/5943422/flanked_tandem_repeat.fasta.zip)

**Comment by rchikhi** [comment]
Excellent, cheers Alla!
