### ISSUE TITLE
diploid assessment

### ISSUE THREAD

**Issue by zhoudreames** [ablab/tandemQUAST#6]
in my diploid species project,I assembly two haplotype centromere of chr12.   their coverage is even and  haven't obviously red heterogeneity signls by using  winnowmap2 and nucplot software.
![image](https://user-images.githubusercontent.com/54714639/124690244-7a562680-df0c-11eb-93dc-59049a23b88d.png)
![image](https://user-images.githubusercontent.com/54714639/124690784-45969f00-df0d-11eb-8fff-cf22da3c7c48.png)

but,their result is very poor by using Tandemtools ,this result show in blew.
![image](https://user-images.githubusercontent.com/54714639/124690473-d8830980-df0c-11eb-9ee7-4d38e87224c8.png)
![image](https://user-images.githubusercontent.com/54714639/124690485-df118100-df0c-11eb-8f53-bf8f0cc6d764.png)
![image](https://user-images.githubusercontent.com/54714639/124690838-5fd07d00-df0d-11eb-921a-8c78b96cd641.png)

that`s why? how to solve it? thanks~

**Comment by zhoudreames** [comment]
i used hifi data to assembly my species genome,there are another result no show here.i used 3 long data (ONT,CLR,HiFi) to assese thier centormere ,in here ,I only show hifi data result by winnowmap2+nucplot,and also show ont data result by tandemtools.

**Comment by zhoudreames** [comment]
@asl @vyahhi @alexeigurevich could you help me ?thanks

**Comment by alexeigurevich** [comment]
Alla @almiheenko is in charge of this project. Could you help?

**Comment by almiheenko** [comment]
Hi. As you can see from the k-mers plot, your assembly has a low number of unique 19-mers, so it is hard to make reliable alignments here. Now we are working on the new version of TandemTools, that uses a longer k and shows much better results on very repetitive assemblies like yours. We are planning to release new version soon and I will notice you if you are interested. Also I can run analysis by myself if you can share your data with me.  
Thank you for using TandemTools!

Best, 
Alla

**Comment by zhoudreames** [comment]
> Alla @almiheenko is in charge of this project. Could you help?

thanks~

**Comment by zhoudreames** [comment]
> Hi. As you can see from the k-mers plot, your assembly has a low number of unique 19-mers, so it is hard to make reliable alignments here. Now we are working on the new version of TandemTools, that uses a longer k and shows much better results on very repetitive assemblies like yours. We are planning to release new version soon and I will notice you if you are interested. Also I can run analysis by myself if you can share your data with me.
> Thank you for using TandemTools!
> 
> Best,
> Alla

thank you for your reply~ how long is your new software be released ？ I have many centromere sequence，If you help me running , I do not know if it will waste your so much time

**Comment by zhoudreames** [comment]
i want to modify your row code，but i dont know how to set the size of kmer，and does it work if I just modify the size of the kmer ？could you tell me ? thanks~

**Comment by zhoudreames** [comment]
@almiheenko thanks you help,i am so sorry for again ask you for another problem

**Comment by almiheenko** [comment]
We hope to prepare a pre-release version in a week or two - is it ok for you? You can try to change k-mer size here https://github.com/ablab/TandemTools/blob/ad668db812fe97f1d7038f6fafe7fbd7508ce038/config.py#L18 However, the maximum possible value in this version is 31 due to some algorithmic limitations, so I am not sure that it will substantially improve results.

**Comment by zhoudreames** [comment]
> We hope to prepare a pre-release version in a week or two - is it ok for you? You can try to change k-mer size here
> 
> https://github.com/ablab/TandemTools/blob/ad668db812fe97f1d7038f6fafe7fbd7508ce038/config.py#L18
> 
> However, the maximum possible value in this version is 31 due to some algorithmic limitations, so I am not sure that it will substantially improve results.

thanks you again~  First ,I‘ll try to the size of kmer  you recommened to  rerun the software,then,I am look forward to
  
 the pre-release version of software ,and will stay focused on the dynamics of your software.

**Comment by almiheenko** [comment]
@zhoudreames Please find here the new version of our tool https://github.com/ablab/TandemMapper2. Please let me know if you have any further questions or need any assistance in running the tool or interpreting the results.

**Comment by zhoudreames** [comment]
> @zhoudreames Please find here the new version of our tool https://github.com/ablab/TandemMapper2. Please let me know if you have any further questions or need any assistance in running the tool or interpreting the results.

thank you~
